require:
  - rubocop-minitest
  - rubocop-disable_syntax

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/DisableSyntax:
  DisableSyntax:
    - unless
    - safe_navigation
    - endless_methods
    - arguments_forwarding
    - numbered_parameters
    - shorthand_hash_syntax
    - and_or_not
    - until
    - percent_literals

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Naming/FileName:
  Exclude:
    - lib/rubocop-disable_syntax.rb

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics:
  Enabled: false
