Style/DisableSyntax:
  Description: 'Forbid some unfavorite ruby syntax, such as `unless`, safe navigation etc.'
  Enabled: true
  VersionAdded: '0.1'
  SupportedDisableSyntax:
    - unless
    - ternary
    - safe_navigation
    - endless_methods
    - arguments_forwarding
    - numbered_parameters
    - pattern_matching
    - shorthand_hash_syntax
    - and_or_not
  DisableSyntax: []
